apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm # Path within the Git repository
    repoURL: https://github.com/immbaur/nd064_course_1
    targetRevision: HEAD
  syncPolicy: {}    